services:
  db:
    image: mysql:8.0
    container_name: kinoxp-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - kinoxp-data:/var/lib/mysql

  pricing:
    build: ../pricing-service
    container_name: kinoxp-pricing
    ports:
      - "8081:8081"

  app:
    build: .
    container_name: kinoxp-app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      PRICING_SERVICE_URL: http://pricing:8081
    depends_on:
      - db
      - pricing

volumes:
  kinoxp-data: