spring.application.name=KinoXP

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

pricing.service.url=${PRICING_SERVICE_URL:http://localhost:8081}
jwt.secret=kinoxp-super-secret-jwt-key-minimum-32-chars

pricing.longfilm.surcharge=20
pricing.3d.surcharge=30
pricing.reservation.fee=25
pricing.group.discount=0.10
pricing.longfilm.threshold=150
pricing.group.threshold=10
pricing.seat.cowboy=0.10
pricing.seat.sofa=50