spring.application.name=KinoXP
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/kinoxp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

pricing.longfilm.surcharge=20
pricing.3d.surcharge=30
pricing.reservation.fee=15
pricing.group.discount=0.07
pricing.longfilm.threshold=170
pricing.group.threshold=5
pricing.seat.cowboy=0.10
pricing.seat.sofa=0.10